
name: chalix-Actions
main: bansystem\BanSystem
version: 3.0.0-B1
author: VMPE Development Team
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
description: A ban system for Pocketmine only, running Latest PMMP-Builds.
